import Link from "next/link";
import { notFound } from "next/navigation";
import { sql } from "@/lib/db";
import { getEvents } from "@/lib/queries";
import StoryCard from "@/components/StoryCard";
import Time from "@/components/Time";
import { hostOf, publisherName } from "@/lib/pipeline";

export const dynamic = "force-dynamic";

const List = ({ items, empty }: { items: string[]; empty: string }) =>
  items?.length ? <ul className="plain">{items.map((x, i) => <li key={i}>{x}</li>)}</ul> : <p className="empty" style={{ textAlign: "left", padding: 0 }}>{empty}</p>;

export default async function EventPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!/^\d+$/.test(id)) notFound();
  const [e] = await sql`select * from events where id = ${id}`;
  if (!e) notFound();
  const articles = await sql`
    select a.title, a.url, a.publisher, a.role, a.published_at, s.name as source_name
    from event_sources es join articles a on a.id = es.article_id join sources s on s.id = es.source_id
    where es.event_id = ${id} order by a.published_at asc`;
  const related = (await getEvents({ category: e.category, hours: 168, limit: 6 })).filter((r) => r.id !== Number(id)).slice(0, 5);

  return (
    <>
      <p><Link href="/">← All news</Link></p>
      <div className="meta">
        <span className={`badge b-${e.importance}`}>{e.importance}</span>
        <span className={`badge v-${e.verification}`}>{e.verification}</span>
        <span>{e.category}</span>·<span>{e.location}</span>·<span>{`${e.source_count} independent source${e.source_count === 1 ? "" : "s"}`}</span>·<span>confidence: {e.confidence}</span>
        {e.is_test && <span className="badge b-test">TEST</span>}
      </div>
      <h1>{e.headline}</h1>
      {e.verification === "CONFLICTING" && <div className="notice bad">Reports currently conflict.</div>}
      {e.verification !== "CONFIRMED" && e.verification !== "CONFLICTING" && <div className="notice">Not confirmed by Saudi authorities (no official source in this event yet).</div>}
      <p>{e.summary}</p>

      <h2>What happened</h2>
      <p>{e.what_happened || e.summary}</p>
      <h2>Confirmed facts <small>(official sources only)</small></h2>
      <List items={e.confirmed_facts} empty="Nothing confirmed by an official source yet." />
      <h2>Claims &amp; reports</h2>
      <List items={e.claims} empty="—" />
      <h2>Unknowns</h2>
      <List items={e.unknowns} empty="—" />

      <h2>Source comparison</h2>
      <div className="card tablewrap">
        <table>
          <thead><tr><th>Source</th><th>Type</th><th>Published</th><th>Headline (original link)</th></tr></thead>
          <tbody>
            {articles.map((a, i) => (
              <tr key={i}>
                <td>{publisherName(a.publisher)}<br /><small>{a.publisher}</small></td>
                <td><span className={`badge ${a.role === "official" ? "v-CONFIRMED" : "b-NORMAL"}`}>{a.role}</span></td>
                <td><Time iso={new Date(a.published_at).toISOString()} /></td>
                <td>
                  {e.is_test ? a.title : <a href={a.url} target="_blank" rel="noopener noreferrer">{a.title}</a>}
                  {hostOf(a.url) === "news.google.com" && <><br /><small>Link redirects via Google News to {a.publisher}</small></>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="meta">Summary generated by {e.ai_provider === "rules" ? "rule-based extraction (no AI)" : `AI (${e.ai_provider})`} from the headlines/snippets above. Verification status is computed from source types, never by the AI.</p>

      <h2>Related coverage</h2>
      {related.length ? related.map((r) => <StoryCard key={r.id} e={r} />) : <p className="empty">No related events this week.</p>}
    </>
  );
}
